---
- name: Deploying Static App
  hosts: all
  become: yes
  tasks:

  - name: Update Apt Repository
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: latest

  - name: Git Clone
    git:
      repo: https://github.com/Paulanisiobi/tetris-light.git
      dest: '{{ ansible_env["PWD"]}}/app'
      single_branch: yes
      version: master
      
      
    
  - name: Copy Nginx configuration to servers
    copy:
      src: /home/ubuntu/ansible2/tetris-light/default
      dest: /etc/nginx/sites-enabled/default
      owner: www-data
      mode: '0644'
    when: ansible_env["PWD"] == "ubuntu"


  - name: Copy Nginx configuration to servers
    copy:
      src: /home/ubuntu/ansible2/tetris-light/default
      dest: /etc/nginx/sites-enabled/default
      owner: www-data
      mode: '0644'
    when: ansible_env["PWD"] == "azureuser" 
  
  - name: print ansible_env
    ansible.builtin.debug:
      msg: '{{ ansible_env["SUDO_USER"]}}/app'
    
         

  - name: Restart Nginx service
    service:
      name: nginx
      state: restarted
     
  